name: this is composite_action
runs:
  using: "composite"
  steps:
    - name: cache_npm
      id: cache
      uses: actions/cache@v4
      with: 
        path: ~/.npm
        key: npm_cache_${{ hasFiles('**/package-lock.json') }}
    - name: install_depndencis
      if: steps.cache.outputs.cache-hit !='true'
      run: npm ci
      shell: bash