name: compsite actions
description: this is for composite actions
runs:
  using: "composite"
  steps:
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: cace_data
      id: cached
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: my_cache_${{hashFiles('**/package-lock.json')}}
    - name: install depndencies
      if: steps.cached.ouputs.cache-hit !='true'
      run: npm ci

