name: matrix_strategy
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        npm_versions: 
          - 10
          - 14
          - 16
        meachines: [ubuntu-latest, macos-26]
    runs-on: ${{matrix.meachines}}
    steps: 
      - name: get_code
        uses: actions/checkout@v4
      - name: install_node_js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.npm_versions}}
      - name: install_depndencis
        run: npm ci
      - name: build_npm
        run: npm run build
