name: re_usable_workflow
on: 
  workflow_call:
    inputs:
      os:
        description: Enter_multiple_os
        type: string
    outputs:
      my_output:
       description: thiis_my_outptu
       value: ${{ jobs.run_matrix_job.outputs.my_output }}
jobs:
  run_matrix_job:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
    runs-on: ${{matrix.os}}
    outputs:
      my_output: ${{ steps.my_op.outpus.my_val }}
    steps:
      - name: greeting_os
        run: echo "this is running on ${{ matrix.os }}"
      - name: set_output
        id: my_op
        run: echo 'my_val=${{ matrix.os }}_output' >> $GITHUB_OUTPUT
