name: workflow_control
on: 
  push:
    branches:
      - main
      - 'feature*'
# declaring global variable
env:
  GLOBAL_VARIABLE: 'global'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint_checkout_code
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: components
          key: ${{hashFiles('**/package-lock.json')}}
      - name: run_lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test_checkout_code
        uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: componets
          key: ${{hashFiles('**/package-lock.json')}}
      - name: run_test
        id: TEST
        run: npm run test
      - name: upload_artifacts
        if: failure() && steps.TEST.outcome=='failure'
        uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: test_results.json
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    outputs:
      job_pass_variable: ${{steps.JOB_VAR.outputs.var_val}}
    # declaring build job variables
    env:
      BUILD_VAR: 'build_var'
    steps:
      - name: build_application
        run: npm run build
      - name: job_pass_variable_assignment
        id: JOB_VAR
        run: echo 'var_val=sudhakar_yadav' >> $GITHUB_OUTPUT
      - name: print_global_and_build_variable
        run: |
          echo "global_variable=${{env.GLOBAL_VARIABLE}}"
          echo "build_bariable=${{env.BUILD_VAR}}"

  deployment:
    runs-on: ubuntu-latest
    needs: build
    environment: PROD
    steps:
      - name: print build job variable
        run: |
          echo "value of build job varialbe: ${{needs.build.outputs.job_pass_variable}}"
      - name: print_enviornment_secrets_and_variables
        run: |
          echo "environment secrets=${{secrets.PROD_SECRET}}"
          echo "environment variable=${{vars.PROD_VAR}}"
  on_completion:
    needs: [test, lint]
    runs-on: ubuntu_latest
    if: failure()
    steps:
      - name: error_message
        run: echo "something went wrong..."