name: workflow_control
on: 
  push:
    branches:
      - main
      - 'feature*'

## declaring global enviornment
env:
  runs_for: test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: download_code
        uses: actions/checkout@v4
      - name: cache and install dependenices
        uses: ./.github/actions/
      - name: running_lint
        uses: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download_code
        uses: actions/checkout@v4
      - name: cache and install dependenices
        uses: ./.github/actions/
      - name: running_test
        uses: npm run test
      - name: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-folder
          path: dab
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    outputs:
      build_var: ${{steps.printoutput.outputs.my_var}}
    steps:
      - name: download_code
        uses: actions/checkout@v4
      - name: build_npm
        run: npm run build
      - name: download_artifact
        uses: actions/dowload-artifact@v4
      - name: list_files
        run: ls
      - name: setting_variable for deployment_step
        id: printoutput
        run: echo 'my_var=${{env.runs_for}}' >> $GITHUB_OUTPUT
  deplpoyment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: print_build_variable
        run: echo printing env_variable from build outputs ${{needs.build.outputs.build_var}}
      - name: failing_step
        id: failing
        run: npm install sudhakar
      - name: moving with step print_sudhakar even after failure
        if: failure() && steps.failing.outcome=='failed'
        run: reached 'sudhakar failed step'
  multiple_run_with_resusable_code:
    strategy:
      matrix:
        os: [macos-26, macos-15,ubuntu-latest,windows-latest]
        include:
          - os: macos-26-intel
        exclude:
          - os: windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: calling re usable code
        uses: ./.github/workflows/reusabulity.yml
        with:
          os: ${{matrix.os}}
  after_job:
    needs: multiple_run_with_resusable_code
    runs-on: ubuntu-latest
    steps:
      - name: get_output_val_from_resusabulity
        run: valut_got ${{needs.multiple_run_with_resusable_code.outpus.my_output}}
        


    



    
